create table if not exists public.access_requests (
  id bigint generated by default as identity primary key,
  email text not null,
  full_name text,
  request_note text,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'denied')),
  requested_at timestamptz not null default timezone('utc', now()),
  reviewed_at timestamptz,
  reviewed_by_email text,
  decision_note text,
  constraint access_requests_email_check check (length(trim(email)) > 3)
);

create index if not exists access_requests_status_requested_at_idx
  on public.access_requests (status, requested_at);

create unique index if not exists access_requests_pending_email_unique
  on public.access_requests ((lower(email)))
  where status = 'pending';

alter table public.access_requests enable row level security;

drop policy if exists access_requests_select_own_or_admin on public.access_requests;
create policy access_requests_select_own_or_admin
on public.access_requests
for select
to authenticated
using (
  public.is_authorized_admin()
  or lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
);

drop policy if exists access_requests_insert_own_pending on public.access_requests;
create policy access_requests_insert_own_pending
on public.access_requests
for insert
to authenticated
with check (
  lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  and status = 'pending'
  and reviewed_at is null
  and reviewed_by_email is null
);

drop policy if exists access_requests_update_admin on public.access_requests;
create policy access_requests_update_admin
on public.access_requests
for update
to authenticated
using (public.is_authorized_admin())
with check (public.is_authorized_admin());

create or replace function public.review_access_request(
  p_request_id bigint,
  p_approve boolean,
  p_decision_note text default null
)
returns public.access_requests
language plpgsql
security definer
set search_path = public
as $function$
declare
  reviewed_request public.access_requests;
begin
  if not public.is_authorized_admin() then
    raise exception 'Only authorized admins can review access requests'
      using errcode = '42501';
  end if;

  update public.access_requests
  set
    status = case when p_approve then 'approved' else 'denied' end,
    reviewed_at = timezone('utc', now()),
    reviewed_by_email = lower(nullif(coalesce(auth.jwt() ->> 'email', ''), '')),
    decision_note = nullif(trim(coalesce(p_decision_note, '')), '')
  where id = p_request_id
    and status = 'pending'
  returning * into reviewed_request;

  if not found then
    raise exception 'Access request not found or already reviewed'
      using errcode = 'P0002';
  end if;

  if p_approve then
    insert into public.authorized_users (email)
    values (lower(reviewed_request.email))
    on conflict do nothing;
  end if;

  return reviewed_request;
end;
$function$;

revoke all on function public.review_access_request(bigint, boolean, text) from public;
grant execute on function public.review_access_request(bigint, boolean, text) to authenticated;
