-- Tracks automatic reminder dispatches for agenda items to prevent duplicate sends.
create table if not exists public.agenda_item_reminder_deliveries (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  agenda_item_index integer not null check (agenda_item_index >= 0),
  agenda_item_start_time bigint not null,
  lead_minutes integer not null check (lead_minutes > 0),
  agenda_item_title text,
  notification_id uuid references public.notifications(id) on delete set null,
  status text not null default 'queued' check (status in ('queued', 'sent', 'failed')),
  response jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  unique (event_id, agenda_item_index, agenda_item_start_time, lead_minutes)
);

create index if not exists agenda_item_reminder_deliveries_event_idx
  on public.agenda_item_reminder_deliveries(event_id);

create index if not exists agenda_item_reminder_deliveries_created_at_idx
  on public.agenda_item_reminder_deliveries(created_at desc);

do $$
declare
  project_url text;
  service_role_key text;
  cron_secret text;
  header_payload jsonb;
  job_command text;
  existing_job record;
begin
  if not exists(select 1 from pg_extension where extname = 'pg_cron')
    or not exists(select 1 from pg_extension where extname = 'pg_net') then
    raise notice 'Skipping agenda reminder cron setup because pg_cron or pg_net is not enabled.';
    return;
  end if;

  select decrypted_secret
    into project_url
  from vault.decrypted_secrets
  where name in ('SUPABASE_URL', 'supabase_url', 'PROJECT_URL', 'project_url')
  order by case name
    when 'SUPABASE_URL' then 0
    when 'supabase_url' then 1
    when 'PROJECT_URL' then 2
    when 'project_url' then 3
    else 4
  end
  limit 1;

  select decrypted_secret
    into service_role_key
  from vault.decrypted_secrets
  where name in ('SUPABASE_SERVICE_ROLE_KEY', 'supabase_service_role_key', 'SERVICE_ROLE_KEY', 'service_role_key')
  order by case name
    when 'SUPABASE_SERVICE_ROLE_KEY' then 0
    when 'supabase_service_role_key' then 1
    when 'SERVICE_ROLE_KEY' then 2
    when 'service_role_key' then 3
    else 4
  end
  limit 1;

  select decrypted_secret
    into cron_secret
  from vault.decrypted_secrets
  where name in ('AGENDA_REMINDER_CRON_SECRET', 'agenda_reminder_cron_secret')
  order by case name
    when 'AGENDA_REMINDER_CRON_SECRET' then 0
    when 'agenda_reminder_cron_secret' then 1
    else 2
  end
  limit 1;

  if project_url is null or service_role_key is null then
    raise notice 'Skipping agenda reminder cron setup because required secrets are missing.';
    return;
  end if;

  header_payload := jsonb_build_object(
    'Content-Type', 'application/json',
    'Authorization', 'Bearer ' || service_role_key
  );

  if cron_secret is not null and length(cron_secret) > 0 then
    header_payload := header_payload || jsonb_build_object('x-agenda-reminder-secret', cron_secret);
  end if;

  job_command := format(
    $cmd$select net.http_post(url := %L, headers := %L::jsonb, body := '{}'::jsonb);$cmd$,
    project_url || '/functions/v1/send-agenda-item-reminders',
    header_payload::text
  );

  for existing_job in
    select jobid
    from cron.job
    where jobname = 'agenda-item-reminders-every-minute'
  loop
    perform cron.unschedule(existing_job.jobid);
  end loop;

  perform cron.schedule(
    'agenda-item-reminders-every-minute',
    '* * * * *',
    job_command
  );
exception
  when others then
    raise notice 'Skipping agenda reminder cron setup due to error: %', sqlerrm;
end
$$;
