create table if not exists public.conferences (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  schedule_title text,
  start_date date,
  end_date date,
  is_active boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint conferences_slug_check
    check (
      slug = lower(trim(slug))
      and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    ),
  constraint conferences_name_check
    check (length(trim(name)) > 0),
  constraint conferences_schedule_title_check
    check (schedule_title is null or length(trim(schedule_title)) > 0),
  constraint conferences_date_range_check
    check (start_date is null or end_date is null or start_date <= end_date)
);

create unique index if not exists conferences_single_active_idx
  on public.conferences ((1))
  where is_active;

create index if not exists conferences_active_updated_idx
  on public.conferences (is_active, updated_at desc);

alter table public.conferences enable row level security;

drop policy if exists conferences_select_public on public.conferences;
create policy conferences_select_public
on public.conferences
for select
using (is_active = true or public.is_authorized_admin());

drop policy if exists conferences_insert_admin on public.conferences;
create policy conferences_insert_admin
on public.conferences
for insert
with check (public.is_authorized_admin());

drop policy if exists conferences_update_admin on public.conferences;
create policy conferences_update_admin
on public.conferences
for update
using (public.is_authorized_admin())
with check (public.is_authorized_admin());

drop policy if exists conferences_delete_admin on public.conferences;
create policy conferences_delete_admin
on public.conferences
for delete
using (public.is_authorized_admin());

update public.conferences
set
  is_active = false,
  updated_at = timezone('utc', now())
where slug <> 'district-37-2026-annual-conference'
  and is_active = true;

insert into public.conferences (
  slug,
  name,
  schedule_title,
  start_date,
  end_date,
  is_active
)
select
  'district-37-2026-annual-conference',
  conference_title,
  conference_title,
  date '2026-05-01',
  date '2026-05-02',
  true
from (
  select coalesce(
    (
      select trim(display_name)
      from public.resources
      where resource_type = 'conference_title'
        and display_name is not null
        and trim(display_name) <> ''
      order by created_at desc
      limit 1
    ),
    'District 37 2026 Annual Conference'
  ) as conference_title
) source
on conflict (slug) do update
set
  name = excluded.name,
  schedule_title = excluded.schedule_title,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  is_active = true,
  updated_at = timezone('utc', now());
