create extension if not exists pgcrypto with schema extensions;

create table if not exists public.event_notification_reminders (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  is_enabled boolean not null default true,
  lead_minutes integer not null default 15 check (lead_minutes >= 0 and lead_minutes <= 1440),
  channel text,
  body_template text,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint event_notification_reminders_channel_check check (
    channel is null
    or (
      length(trim(channel)) > 0
      and length(trim(channel)) <= 900
      and trim(channel) ~ '^[A-Za-z0-9\-_.~%]+$'
    )
  )
);

create index if not exists event_notification_reminders_event_sort_idx
  on public.event_notification_reminders(event_id, sort_order, id);

alter table public.event_notification_reminders enable row level security;

drop policy if exists event_notification_reminders_admin_read on public.event_notification_reminders;
create policy event_notification_reminders_admin_read
  on public.event_notification_reminders
  for select
  to authenticated
  using (is_authorized_admin());

drop policy if exists event_notification_reminders_admin_write on public.event_notification_reminders;
create policy event_notification_reminders_admin_write
  on public.event_notification_reminders
  for all
  to authenticated
  using (is_authorized_admin())
  with check (is_authorized_admin());

insert into public.event_notification_reminders (
  event_id,
  is_enabled,
  lead_minutes,
  channel,
  body_template,
  sort_order
)
select
  e.id,
  true,
  e.notification_lead_minutes,
  nullif(trim(e.notification_channel), ''),
  null,
  0
from public.events e
where e.notify_before = true
  and not exists (
    select 1
    from public.event_notification_reminders r
    where r.event_id = e.id
  );

alter table public.notifications
  add column if not exists scheduled_for timestamptz,
  add column if not exists sent_at timestamptz,
  add column if not exists source text not null default 'manual',
  add column if not exists source_dedupe_key text;

update public.notifications
set scheduled_for = created_at
where status = 'queued'
  and scheduled_for is null;

update public.notifications
set sent_at = created_at
where status = 'sent'
  and sent_at is null;

create index if not exists notifications_status_scheduled_for_idx
  on public.notifications(status, scheduled_for);

create unique index if not exists notifications_source_dedupe_key_unique
  on public.notifications(source_dedupe_key)
  where source_dedupe_key is not null;

do $$
declare
  cron_secret text;
  header_payload jsonb;
  process_job_command text;
  existing_job record;
begin
  if not exists (select 1 from pg_extension where extname = 'pg_cron')
    or not exists (select 1 from pg_extension where extname = 'pg_net') then
    raise exception 'pg_cron and pg_net must be enabled before scheduling notification processors';
  end if;

  insert into public.system_runtime_settings(key, value)
  values ('event_reminder_cron_secret', encode(extensions.gen_random_bytes(32), 'hex'))
  on conflict (key) do nothing;

  select value
    into cron_secret
  from public.system_runtime_settings
  where key = 'event_reminder_cron_secret'
  limit 1;

  if cron_secret is null or length(cron_secret) = 0 then
    raise exception 'event_reminder_cron_secret is missing from system_runtime_settings';
  end if;

  header_payload := jsonb_build_object(
    'Content-Type', 'application/json',
    'x-event-reminder-secret', cron_secret
  );

  process_job_command := format(
    $cmd$select net.http_post(url := %L, headers := %L::jsonb, body := '{}'::jsonb);$cmd$,
    'https://yarbshxeeufpgquawcuy.supabase.co/functions/v1/process-scheduled-notifications',
    header_payload::text
  );

  for existing_job in
    select jobid
    from cron.job
    where jobname in ('process-scheduled-notifications-every-minute')
  loop
    perform cron.unschedule(existing_job.jobid);
  end loop;

  perform cron.schedule(
    'process-scheduled-notifications-every-minute',
    '* * * * *',
    process_job_command
  );
end
$$;
