-- Hard cutover: remove agenda-item reminders and switch to event-level reminders.
create extension if not exists pgcrypto with schema extensions;

alter table public.events
  add column notify_before boolean not null default false,
  add column notification_lead_minutes integer not null default 15,
  add constraint events_notification_lead_minutes_check
    check (notification_lead_minutes > 0 and notification_lead_minutes <= 1440);

alter table public.events
  drop column agenda;

drop table if exists public.event_reminder_deliveries cascade;
create table public.event_reminder_deliveries (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  event_start_time bigint not null,
  lead_minutes integer not null check (lead_minutes > 0 and lead_minutes <= 1440),
  event_title text,
  notification_id uuid references public.notifications(id) on delete set null,
  status text not null default 'queued' check (status in ('queued', 'sent', 'failed')),
  response jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  unique (event_id, event_start_time, lead_minutes)
);

create index event_reminder_deliveries_event_idx
  on public.event_reminder_deliveries(event_id);

create index event_reminder_deliveries_created_at_idx
  on public.event_reminder_deliveries(created_at desc);

drop table if exists public.agenda_item_reminder_deliveries cascade;

delete from public.system_runtime_settings
where key = 'agenda_reminder_cron_secret';

insert into public.system_runtime_settings(key, value)
values ('event_reminder_cron_secret', encode(extensions.gen_random_bytes(32), 'hex'))
on conflict (key) do nothing;

do $$
declare
  cron_secret text;
  header_payload jsonb;
  job_command text;
  existing_job record;
begin
  if not exists(select 1 from pg_extension where extname = 'pg_cron')
    or not exists(select 1 from pg_extension where extname = 'pg_net') then
    raise exception 'pg_cron and pg_net must be enabled before scheduling event reminders';
  end if;

  select value
    into cron_secret
  from public.system_runtime_settings
  where key = 'event_reminder_cron_secret'
  limit 1;

  if cron_secret is null or length(cron_secret) = 0 then
    raise exception 'event_reminder_cron_secret is missing from system_runtime_settings';
  end if;

  header_payload := jsonb_build_object(
    'Content-Type', 'application/json',
    'x-event-reminder-secret', cron_secret
  );

  job_command := format(
    $cmd$select net.http_post(url := %L, headers := %L::jsonb, body := '{}'::jsonb);$cmd$,
    'https://yarbshxeeufpgquawcuy.supabase.co/functions/v1/send-event-reminders',
    header_payload::text
  );

  for existing_job in
    select jobid
    from cron.job
    where jobname in ('agenda-item-reminders-every-minute', 'event-reminders-every-minute')
  loop
    perform cron.unschedule(existing_job.jobid);
  end loop;

  perform cron.schedule(
    'event-reminders-every-minute',
    '* * * * *',
    job_command
  );
end
$$;
