package com.district37tm.fridaylist

import com.district37tm.fridaylist.domain.BackendEventDetails
import com.district37tm.fridaylist.domain.TimeRange
import java.time.ZoneId
import java.time.ZonedDateTime

val fridayList = listOf(
    BackendEventDetails(
        name = "Friday, May 2, 2:00 PM - 5:45 PM",
        timeRanges = listOf(
            TimeRange(
                startTime = ZonedDateTime.of(2025, 5, 2, 14, 0, 0, 0, ZoneId.of("America/New_York")).toEpochSecond() * 1000,
                endTime = ZonedDateTime.of(2025, 5, 2, 17, 45, 0, 0, ZoneId.of("America/New_York")).toEpochSecond() * 1000
            )
        ),
        location = "District 37 Headquarters",
        description = "Welcome and registration."
    ),
    BackendEventDetails(
        name = "Friday, May 2, 6:00 PM - 9:00 PM",
        timeRanges = listOf(
            TimeRange(
                startTime = ZonedDateTime.of(2025, 5, 2, 18, 0, 0, 0, ZoneId.of("America/New_York")).toEpochSecond() * 1000,
                endTime = ZonedDateTime.of(2025, 5, 2, 21, 0, 0, 0, ZoneId.of("America/New_York")).toEpochSecond() * 1000
            )
        ),
        location = "District 37 Headquarters",
        description = "Opening reception."
    ),
    BackendEventDetails(
        name = "Saturday, May 3, 9:00 AM - 12:00 PM\nSaturday, May 3, 1:00 PM - 4:00 PM",
        timeRanges = listOf(
            TimeRange(
                startTime = ZonedDateTime.of(2025, 5, 3, 9, 0, 0, 0, ZoneId.of("America/New_York")).toEpochSecond() * 1000,
                endTime = ZonedDateTime.of(2025, 5, 3, 12, 0, 0, 0, ZoneId.of("America/New_York")).toEpochSecond() * 1000
            ),
            TimeRange(
                startTime = ZonedDateTime.of(2025, 5, 3, 13, 0, 0, 0, ZoneId.of("America/New_York")).toEpochSecond() * 1000,
                endTime = ZonedDateTime.of(2025, 5, 3, 16, 0, 0, 0, ZoneId.of("America/New_York")).toEpochSecond() * 1000
            )
        ),
        location = "District 37 Headquarters",
        description = "Workshops and panels."
    ),
    BackendEventDetails(
        name = "Sunday, May 4, 10:00 AM - 3:00 PM",
        timeRanges = listOf(
            TimeRange(
                startTime = ZonedDateTime.of(2025, 5, 4, 10, 0, 0, 0, ZoneId.of("America/New_York")).toEpochSecond() * 1000,
                endTime = ZonedDateTime.of(2025, 5, 4, 15, 0, 0, 0, ZoneId.of("America/New_York")).toEpochSecond() * 1000
            )
        ),
        location = "District 37 Headquarters",
        description = "Closing ceremony."
    )
)
